// Builds two small font subsets from the Fontsource files, so the first paint downloads less:
//
//   src/fonts/archivo-display.woff2  Archivo with width + weight axes, uppercase only.
//                                    The display style is always uppercase (CSS text-transform).
//   src/fonts/kalam-note.woff2       Kalam, only the characters of the hero margin note.
//
// index.css declares these after the full Fontsource faces with a matching unicode-range,
// so the browser prefers them and falls back to the full fonts for any other character.
// Run `npm run fonts` after changing the margin note or updating the Fontsource packages.
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import subsetFont from "subset-font";

const root = resolve(import.meta.dirname, "..");
const outDir = resolve(root, "src/fonts");
await mkdir(outDir, { recursive: true });

const upper = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
const digits = "0123456789";
const punctuation = " !\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~–—‘’“”·…•→";

const site = await readFile(resolve(root, "src/content/site.ts"), "utf8");
const note = site.match(/marginNote:\s*"([^"]*)"/)?.[1];
if (!note) throw new Error("fonts: could not find hero.marginNote in src/content/site.ts");

async function subset(pkg, file, text, out) {
  const source = await readFile(resolve(root, "node_modules", pkg, "files", file));
  const result = await subsetFont(source, text, { targetFormat: "woff2" });
  await writeFile(resolve(outDir, out), result);
  console.log(`fonts: ${out} ${Math.round(result.length / 1024)} KB (from ${Math.round(source.length / 1024)} KB)`);
}

/** "ABC" → "U+41-43": the exact characters a subset covers */
function unicodeRange(text) {
  const points = [...new Set([...text].map((c) => c.codePointAt(0)))].sort((a, b) => a - b);
  const ranges = [];
  for (const p of points) {
    const last = ranges[ranges.length - 1];
    if (last && p === last[1] + 1) last[1] = p;
    else ranges.push([p, p]);
  }
  const hex = (n) => n.toString(16).toUpperCase();
  return ranges.map(([a, b]) => (a === b ? `U+${hex(a)}` : `U+${hex(a)}-${hex(b)}`)).join(", ");
}

const displayText = upper + digits + punctuation;
const noteText = [...new Set(note + " .")].join("");

await subset("@fontsource-variable/archivo", "archivo-latin-wdth-normal.woff2", displayText, "archivo-display.woff2");
await subset("@fontsource/kalam", "kalam-latin-400-normal.woff2", noteText, "kalam-note.woff2");

const css = `/* Generated by scripts/fonts.mjs. Run \`npm run fonts\` instead of editing. */
@font-face {
  font-family: "Archivo Variable";
  font-style: normal;
  font-display: swap;
  font-weight: 100 900;
  font-stretch: 62% 125%;
  src: url("./archivo-display.woff2") format("woff2-variations");
  unicode-range: ${unicodeRange(displayText)};
}

@font-face {
  font-family: "Kalam";
  font-style: normal;
  font-display: swap;
  font-weight: 400;
  src: url("./kalam-note.woff2") format("woff2");
  unicode-range: ${unicodeRange(noteText)};
}
`;
await writeFile(resolve(outDir, "fonts.css"), css);
console.log("fonts: wrote src/fonts/fonts.css");
